"""Simple per-user multilingual system. Add/edit languages here without changing handlers."""
from aiogram.utils.keyboard import InlineKeyboardBuilder
from utils.buttons import btn
from utils.premium_emoji import emoji_id

LANGUAGES = {
    'en': '🇬🇧 English', 'hi': '🇮🇳 हिन्दी', 'ru': '🇷🇺 Русский', 'tr': '🇹🇷 Türkçe',
    'id': '🇮🇩 Indonesia', 'es': '🇪🇸 Español', 'fr': '🇫🇷 Français', 'de': '🇩🇪 Deutsch',
    'ar': '🇸🇦 العربية', 'pt': '🇵🇹 Português'
}
T = {
'en': {
'home':'Home','welcome':'Welcome to the Content Shop','choose':'Choose an option below.','products':'View Products','wallet':'My Wallet','profile':'Profile','reviews':'Reviews','refer':'Refer & Earn','support':'Support','sell':'Sell Now','language':'Change Language','add_money':'Add Money','back':'Back','cancel':'Cancel','search':'Search Products','choose_category':'Choose a Category','choose_subcategory':'Choose a Sub-category','available':'Available Products','no_products':'No products available.','buy1':'Buy 1','buy2':'Buy 2','custom':'Custom Quantity','insufficient':'Insufficient Balance','price':'Price','balance':'Balance','stock':'Stock','unlimited':'Unlimited','add_funds':'Add funds to continue.','purchase_ok':'Purchase Successful','quantity':'Quantity','paid':'Paid','left_balance':'Left Balance','order_id':'Order ID','product_unavailable':'Product unavailable','search_prompt':'Send product name or keyword.','custom_prompt':'Send the quantity as a number.','invalid_qty':'Enter a valid positive quantity.','processing':'Processing purchase...','recharge':'Recharge / Add Money','profile_name':'Name','username':'Username','contact':'Contact','referral_link':'Your referral link','language_title':'Choose your language','language_saved':'Language changed to {language}.','join_required':'Join Required','join_text':'Please join the required channels first.','joined':'I Joined','join_both':'Please join both required channels.','restricted':'Your account is restricted.','support_text':'Contact: {support}','sell_text':'To list your content, contact {support}','reviews_text':'Open our reviews page below.','reviews_open':'Open Reviews'
},
'hi': {'home':'होम','welcome':'कंटेंट शॉप में आपका स्वागत है','choose':'नीचे से एक विकल्प चुनें।','products':'प्रोडक्ट देखें','wallet':'मेरा वॉलेट','profile':'प्रोफ़ाइल','reviews':'रिव्यू','refer':'रेफर करें और कमाएँ','support':'सपोर्ट','sell':'अभी बेचें','language':'भाषा बदलें','add_money':'पैसे जोड़ें','back':'वापस','cancel':'रद्द करें','search':'प्रोडक्ट खोजें','choose_category':'कैटेगरी चुनें','choose_subcategory':'सब-कैटेगरी चुनें','available':'उपलब्ध प्रोडक्ट','no_products':'कोई प्रोडक्ट उपलब्ध नहीं है।','buy1':'1 खरीदें','buy2':'2 खरीदें','custom':'कस्टम मात्रा','insufficient':'बैलेंस कम है','price':'कीमत','balance':'बैलेंस','stock':'स्टॉक','unlimited':'अनलिमिटेड','add_funds':'जारी रखने के लिए बैलेंस जोड़ें।','purchase_ok':'खरीद सफल हुई','quantity':'मात्रा','paid':'भुगतान','left_balance':'बचा बैलेंस','order_id':'ऑर्डर ID','product_unavailable':'प्रोडक्ट उपलब्ध नहीं है','search_prompt':'प्रोडक्ट का नाम या कीवर्ड भेजें।','custom_prompt':'मात्रा संख्या में भेजें।','invalid_qty':'सही मात्रा दर्ज करें।','processing':'खरीद प्रोसेस हो रही है...','recharge':'रिचार्ज / पैसे जोड़ें','profile_name':'नाम','username':'यूज़रनेम','contact':'संपर्क','referral_link':'आपका रेफरल लिंक','language_title':'अपनी भाषा चुनें','language_saved':'भाषा बदल दी गई: {language}','join_required':'जॉइन करना आवश्यक है','join_text':'पहले आवश्यक चैनल जॉइन करें।','joined':'मैंने जॉइन किया','join_both':'कृपया दोनों आवश्यक चैनल जॉइन करें।','restricted':'आपका अकाउंट प्रतिबंधित है।','support_text':'संपर्क: {support}','sell_text':'अपना कंटेंट लिस्ट करने के लिए संपर्क करें: {support}','reviews_text':'हमारा रिव्यू पेज नीचे खोलें।','reviews_open':'रिव्यू खोलें'},
'ru': {'home':'Главная','welcome':'Добро пожаловать в магазин контента','choose':'Выберите действие ниже.','products':'Товары','wallet':'Мой кошелёк','profile':'Профиль','reviews':'Отзывы','refer':'Пригласи и заработай','support':'Поддержка','sell':'Продать','language':'Изменить язык','add_money':'Пополнить','back':'Назад','cancel':'Отмена','search':'Поиск товаров','choose_category':'Выберите категорию','choose_subcategory':'Выберите подкатегорию','available':'Доступные товары','no_products':'Товаров нет.','buy1':'Купить 1','buy2':'Купить 2','custom':'Свое количество','insufficient':'Недостаточно средств','price':'Цена','balance':'Баланс','stock':'Остаток','unlimited':'Без ограничений','add_funds':'Пополните баланс, чтобы продолжить.','purchase_ok':'Покупка успешна','quantity':'Количество','paid':'Оплачено','left_balance':'Остаток','order_id':'ID заказа','product_unavailable':'Товар недоступен','search_prompt':'Отправьте название или ключевое слово.','custom_prompt':'Отправьте количество числом.','invalid_qty':'Введите корректное положительное количество.','processing':'Обработка покупки...','recharge':'Пополнить баланс','profile_name':'Имя','username':'Имя пользователя','contact':'Контакт','referral_link':'Ваша реферальная ссылка','language_title':'Выберите язык','language_saved':'Язык изменён: {language}','join_required':'Требуется подписка','join_text':'Сначала подпишитесь на обязательные каналы.','joined':'Я подписался','join_both':'Подпишитесь на оба обязательных канала.','restricted':'Ваш аккаунт ограничен.','support_text':'Контакт: {support}','sell_text':'Чтобы разместить контент, свяжитесь: {support}','reviews_text':'Откройте страницу отзывов ниже.','reviews_open':'Открыть отзывы'},
}
T.update({
 'tr': dict(T['en'], home='Ana Menü', welcome='İçerik Mağazasına Hoş Geldiniz', choose='Aşağıdan bir seçenek seçin.', products='Ürünleri Gör', wallet='Cüzdanım', profile='Profil', reviews='Yorumlar', refer='Davet Et ve Kazan', support='Destek', sell='Şimdi Sat', language='Dili Değiştir', add_money='Para Ekle', back='Geri', cancel='İptal', search='Ürün Ara', choose_category='Kategori Seçin', choose_subcategory='Alt Kategori Seçin', available='Mevcut Ürünler', no_products='Ürün bulunamadı.', buy1='1 Satın Al', buy2='2 Satın Al', custom='Özel Miktar', insufficient='Yetersiz Bakiye', price='Fiyat', balance='Bakiye', stock='Stok', unlimited='Sınırsız', add_funds='Devam etmek için bakiye ekleyin.', purchase_ok='Satın Alma Başarılı', quantity='Miktar', paid='Ödenen', left_balance='Kalan Bakiye', order_id='Sipariş ID', product_unavailable='Ürün mevcut değil', search_prompt='Ürün adı veya anahtar kelime gönderin.', custom_prompt='Miktarı sayı olarak gönderin.', invalid_qty='Geçerli bir miktar girin.', processing='Satın alma işleniyor...', recharge='Bakiye Yükle', profile_name='Ad', username='Kullanıcı adı', contact='İletişim', referral_link='Referans bağlantınız', language_title='Dilinizi seçin', language_saved='Dil değiştirildi: {language}', join_required='Katılım Gerekli', join_text='Önce gerekli kanallara katılın.', joined='Katıldım', join_both='Lütfen iki kanala da katılın.', restricted='Hesabınız kısıtlandı.', support_text='İletişim: {support}', sell_text='İçeriğinizi listelemek için iletişime geçin: {support}', reviews_text='Yorumlar sayfamızı aşağıdan açın.', reviews_open='Yorumları Aç'),
 'id': dict(T['en'], home='Beranda', welcome='Selamat Datang di Toko Konten', choose='Pilih opsi di bawah.', products='Lihat Produk', wallet='Dompet Saya', profile='Profil', reviews='Ulasan', refer='Ajak & Dapatkan', support='Dukungan', sell='Jual Sekarang', language='Ganti Bahasa', add_money='Tambah Saldo', back='Kembali', cancel='Batal', search='Cari Produk', choose_category='Pilih Kategori', choose_subcategory='Pilih Subkategori', available='Produk Tersedia', no_products='Tidak ada produk.', buy1='Beli 1', buy2='Beli 2', custom='Jumlah Kustom', insufficient='Saldo Tidak Cukup', price='Harga', balance='Saldo', stock='Stok', unlimited='Tidak Terbatas', add_funds='Tambahkan saldo untuk melanjutkan.', purchase_ok='Pembelian Berhasil', quantity='Jumlah', paid='Dibayar', left_balance='Sisa Saldo', order_id='ID Pesanan', product_unavailable='Produk tidak tersedia', search_prompt='Kirim nama produk atau kata kunci.', custom_prompt='Kirim jumlah sebagai angka.', invalid_qty='Masukkan jumlah positif yang valid.', processing='Memproses pembelian...', recharge='Isi Saldo', profile_name='Nama', username='Nama pengguna', contact='Kontak', referral_link='Tautan referral Anda', language_title='Pilih bahasa', language_saved='Bahasa diubah menjadi {language}.', join_required='Wajib Bergabung', join_text='Silakan bergabung dengan kanal yang diwajibkan.', joined='Saya Sudah Bergabung', join_both='Silakan bergabung dengan kedua kanal.', restricted='Akun Anda dibatasi.', support_text='Kontak: {support}', sell_text='Untuk mencantumkan konten, hubungi {support}', reviews_text='Buka halaman ulasan kami di bawah.', reviews_open='Buka Ulasan'),
 'es': dict(T['en'], home='Inicio', welcome='Bienvenido a la Tienda de Contenido', choose='Elige una opción.', products='Ver Productos', wallet='Mi Billetera', profile='Perfil', reviews='Reseñas', refer='Invita y Gana', support='Soporte', sell='Vender Ahora', language='Cambiar Idioma', add_money='Añadir Dinero', back='Atrás', cancel='Cancelar', search='Buscar Productos', choose_category='Elige una Categoría', choose_subcategory='Elige una Subcategoría', available='Productos Disponibles', no_products='No hay productos.', buy1='Comprar 1', buy2='Comprar 2', custom='Cantidad Personalizada', insufficient='Saldo Insuficiente', price='Precio', balance='Saldo', stock='Stock', unlimited='Ilimitado', add_funds='Añade saldo para continuar.', purchase_ok='Compra Exitosa', quantity='Cantidad', paid='Pagado', left_balance='Saldo Restante', order_id='ID del Pedido', product_unavailable='Producto no disponible', search_prompt='Envía el nombre o palabra clave.', custom_prompt='Envía la cantidad como número.', invalid_qty='Introduce una cantidad válida.', processing='Procesando compra...', recharge='Recargar Saldo', profile_name='Nombre', username='Usuario', contact='Contacto', referral_link='Tu enlace de referido', language_title='Elige tu idioma', language_saved='Idioma cambiado a {language}.', join_required='Unirse es Obligatorio', join_text='Únete primero a los canales requeridos.', joined='Ya Me Uní', join_both='Únete a ambos canales requeridos.', restricted='Tu cuenta está restringida.', support_text='Contacto: {support}', sell_text='Para listar contenido, contacta con {support}', reviews_text='Abre nuestra página de reseñas abajo.', reviews_open='Abrir Reseñas'),
 'fr': dict(T['en'], home='Accueil', welcome='Bienvenue dans la boutique de contenu', choose='Choisissez une option ci-dessous.', products='Voir les Produits', wallet='Mon Portefeuille', profile='Profil', reviews='Avis', refer='Parrainer et Gagner', support='Support', sell='Vendre Maintenant', language='Changer de Langue', add_money='Ajouter de l’Argent', back='Retour', cancel='Annuler', search='Rechercher des Produits', choose_category='Choisissez une Catégorie', choose_subcategory='Choisissez une Sous-catégorie', available='Produits Disponibles', no_products='Aucun produit disponible.', buy1='Acheter 1', buy2='Acheter 2', custom='Quantité Personnalisée', insufficient='Solde Insuffisant', price='Prix', balance='Solde', stock='Stock', unlimited='Illimité', add_funds='Ajoutez des fonds pour continuer.', purchase_ok='Achat Réussi', quantity='Quantité', paid='Payé', left_balance='Solde Restant', order_id='ID de Commande', product_unavailable='Produit indisponible', search_prompt='Envoyez le nom ou un mot-clé.', custom_prompt='Envoyez la quantité sous forme de nombre.', invalid_qty='Entrez une quantité positive valide.', processing='Achat en cours...', recharge='Recharger', profile_name='Nom', username='Nom d’utilisateur', contact='Contact', referral_link='Votre lien de parrainage', language_title='Choisissez votre langue', language_saved='Langue changée en {language}.', join_required='Abonnement Requis', join_text='Rejoignez d’abord les canaux requis.', joined='J’ai Rejoint', join_both='Rejoignez les deux canaux requis.', restricted='Votre compte est restreint.', support_text='Contact : {support}', sell_text='Pour publier votre contenu, contactez {support}', reviews_text='Ouvrez notre page d’avis ci-dessous.', reviews_open='Ouvrir les Avis'),
 'de': dict(T['en'], home='Startseite', welcome='Willkommen im Content-Shop', choose='Wähle eine Option.', products='Produkte Anzeigen', wallet='Mein Wallet', profile='Profil', reviews='Bewertungen', refer='Freunde Werben', support='Support', sell='Jetzt Verkaufen', language='Sprache Ändern', add_money='Geld Hinzufügen', back='Zurück', cancel='Abbrechen', search='Produkte Suchen', choose_category='Kategorie Wählen', choose_subcategory='Unterkategorie Wählen', available='Verfügbare Produkte', no_products='Keine Produkte verfügbar.', buy1='1 Kaufen', buy2='2 Kaufen', custom='Benutzerdefinierte Menge', insufficient='Unzureichendes Guthaben', price='Preis', balance='Guthaben', stock='Bestand', unlimited='Unbegrenzt', add_funds='Guthaben hinzufügen, um fortzufahren.', purchase_ok='Kauf Erfolgreich', quantity='Menge', paid='Bezahlt', left_balance='Restguthaben', order_id='Bestell-ID', product_unavailable='Produkt nicht verfügbar', search_prompt='Produktname oder Stichwort senden.', custom_prompt='Menge als Zahl senden.', invalid_qty='Gültige positive Menge eingeben.', processing='Kauf wird verarbeitet...', recharge='Guthaben Aufladen', profile_name='Name', username='Benutzername', contact='Kontakt', referral_link='Dein Empfehlungslink', language_title='Sprache auswählen', language_saved='Sprache geändert zu {language}.', join_required='Beitritt Erforderlich', join_text='Bitte zuerst die erforderlichen Kanäle abonnieren.', joined='Ich bin beigetreten', join_both='Bitte beiden Kanälen beitreten.', restricted='Dein Konto ist eingeschränkt.', support_text='Kontakt: {support}', sell_text='Für die Auflistung deiner Inhalte kontaktiere {support}', reviews_text='Öffne unten unsere Bewertungsseite.', reviews_open='Bewertungen Öffnen'),
 'ar': dict(T['en'], home='الرئيسية', welcome='مرحباً بك في متجر المحتوى', choose='اختر خياراً أدناه.', products='عرض المنتجات', wallet='محفظتي', profile='الملف الشخصي', reviews='التقييمات', refer='ادعُ واربح', support='الدعم', sell='بع الآن', language='تغيير اللغة', add_money='إضافة رصيد', back='رجوع', cancel='إلغاء', search='بحث عن المنتجات', choose_category='اختر الفئة', choose_subcategory='اختر الفئة الفرعية', available='المنتجات المتاحة', no_products='لا توجد منتجات متاحة.', buy1='شراء 1', buy2='شراء 2', custom='كمية مخصصة', insufficient='الرصيد غير كافٍ', price='السعر', balance='الرصيد', stock='المخزون', unlimited='غير محدود', add_funds='أضف رصيداً للمتابعة.', purchase_ok='تم الشراء بنجاح', quantity='الكمية', paid='المدفوع', left_balance='الرصيد المتبقي', order_id='رقم الطلب', product_unavailable='المنتج غير متاح', search_prompt='أرسل اسم المنتج أو كلمة مفتاحية.', custom_prompt='أرسل الكمية كرقم.', invalid_qty='أدخل كمية موجبة صحيحة.', processing='جارٍ معالجة الشراء...', recharge='شحن الرصيد', profile_name='الاسم', username='اسم المستخدم', contact='التواصل', referral_link='رابط الإحالة الخاص بك', language_title='اختر لغتك', language_saved='تم تغيير اللغة إلى {language}.', join_required='الانضمام مطلوب', join_text='يرجى الانضمام إلى القنوات المطلوبة أولاً.', joined='انضممت', join_both='يرجى الانضمام إلى القناتين المطلوبتين.', restricted='حسابك مقيّد.', support_text='التواصل: {support}', sell_text='لإضافة محتواك تواصل مع {support}', reviews_text='افتح صفحة التقييمات أدناه.', reviews_open='فتح التقييمات'),
 'pt': dict(T['en'], home='Início', welcome='Bem-vindo à Loja de Conteúdo', choose='Escolha uma opção abaixo.', products='Ver Produtos', wallet='Minha Carteira', profile='Perfil', reviews='Avaliações', refer='Indique e Ganhe', support='Suporte', sell='Vender Agora', language='Mudar Idioma', add_money='Adicionar Dinheiro', back='Voltar', cancel='Cancelar', search='Pesquisar Produtos', choose_category='Escolha uma Categoria', choose_subcategory='Escolha uma Subcategoria', available='Produtos Disponíveis', no_products='Nenhum produto disponível.', buy1='Comprar 1', buy2='Comprar 2', custom='Quantidade Personalizada', insufficient='Saldo Insuficiente', price='Preço', balance='Saldo', stock='Estoque', unlimited='Ilimitado', add_funds='Adicione saldo para continuar.', purchase_ok='Compra Bem-sucedida', quantity='Quantidade', paid='Pago', left_balance='Saldo Restante', order_id='ID do Pedido', product_unavailable='Produto indisponível', search_prompt='Envie o nome ou palavra-chave.', custom_prompt='Envie a quantidade como número.', invalid_qty='Digite uma quantidade positiva válida.', processing='Processando compra...', recharge='Recarregar Saldo', profile_name='Nome', username='Usuário', contact='Contato', referral_link='Seu link de indicação', language_title='Escolha seu idioma', language_saved='Idioma alterado para {language}.', join_required='Entrada Obrigatória', join_text='Entre primeiro nos canais obrigatórios.', joined='Já Entrei', join_both='Entre nos dois canais obrigatórios.', restricted='Sua conta está restrita.', support_text='Contato: {support}', sell_text='Para listar seu conteúdo, entre em contato com {support}', reviews_text='Abra nossa página de avaliações abaixo.', reviews_open='Abrir Avaliações')
})

# UI strings introduced by the upgraded support/referral/shop flows.
_COMMON_EXTRAS = {
    'choose_product': 'Choose the product to buy below.',
    'referral_rules': 'Share your link. A reward is credited after the referred user completes verification.',
    'successful_referrals': 'Successful referrals',
    'total_earned': 'Total earned',
    'credit_per_referral': 'Credit per successful referral',
}
for _lang in T.values():
    for _key, _value in _COMMON_EXTRAS.items():
        _lang.setdefault(_key, _value)

async def get_lang(db, user_id):
    u = await db.users.find_one({'telegram_id': user_id}, {'language':1})
    return (u or {}).get('language','en')

async def t(db, user_id, key, **kwargs):
    lang = await get_lang(db, user_id)
    return T.get(lang, T['en']).get(key, T['en'].get(key,key)).format(**kwargs)

def language_keyboard():
    # Use the same single-icon rule as every other button.
    b = InlineKeyboardBuilder()
    for code, name in LANGUAGES.items():
        label = name.split(' ', 1)[1] if emoji_id('language') and ' ' in name else name
        b.add(btn(label, callback_data=f'lang:{code}', emoji_key='language'))
    b.adjust(2)
    return b.as_markup()
